**# Data Ingestion, Initial Inspection and Dataframe Allocation**

NOTE: THIS NOTEBOOK IS ONLY INTENDED TO GIVE A STARTING POINT TO EXPLORATIONS. THIS IS NOT THE OFFICIAL CLEANING PIPELIND WE USED FOR THE REVIEWS PROJECT!

**Goals:**  
1. Load and inspect all raw datasets in order to understand their structure, data quality, and differences before cleaning and normalization.
2. Convert JSON reviews file to CSV
3. Create a dataframes of each csv file and compile them all into a master_reviews dataframe.
4. Save master_reviews as CSV to be used for data cleaning.

This notebook focuses only on:
- Importing and converting the data
- Understanding schemas
- Identifying early data quality issues

No cleaning is applied yet.

*PLEASE NOTE! This notebook assumes a folder structure on Google Drive with the following path:*
/content/drive/MyDrive/reviews_datasets/...

In [ ]:
#mount google drive folder with main datasets
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Google Reviews DF

## Import JSON Google Reviews and convert to CSV

In [ ]:
import pandas as pd
pd.read_json('/content/drive/MyDrive/Essentis/data/reviews.json').to_csv('output.csv', index=False)

In [ ]:
import os
os.listdir()

['.config', 'drive', 'output.csv', 'sample_data']

In [ ]:
df = pd.read_csv('output.csv')
df.head()

,reviewer_name,reviewer_profile_image,is_local_guide,review_count,rating,review_date,review_text,link,photo_count,review_images
0,irine divya,https://lh3.googleusercontent.com/a/ACg8ocK827...,False,5 reviews,5,a month ago,"I am a Data Analyst Bootcamp student, and my e...",https://www.google.com/maps/contrib/1028908243...,NaN,NaN
1,Asieh Sharifi,https://lh3.googleusercontent.com/a-/ALV-UjXnN...,True,44 reviews,5,a month ago,Great UX/UI Bootcamp ExperienceI attended the ...,https://www.google.com/maps/contrib/1134308022...,33 photos,NaN
2,Margarita M,https://lh3.googleusercontent.com/a-/ALV-UjUnh...,False,13 reviews,5,a month ago,I recently completed a UX/UI Product Design pr...,https://www.google.com/maps/contrib/1115744527...,104 photos,NaN
3,Marvin,https://lh3.googleusercontent.com/a-/ALV-UjWpD...,False,10 reviews,5,3 months ago,I completed the Full-Stack Web & App Developme...,https://www.google.com/maps/contrib/1168523753...,3 photos,NaN
4,Majdi Alachkar,https://lh3.googleusercontent.com/a-/ALV-UjX6p...,False,3 reviews,5,2 months ago,I completed the Data Science Bootcamp at WBS S...,https://www.google.com/maps/contrib/1021783225...,3 photos,NaN

In [ ]:
df.shape

(256, 10)

In [ ]:
# this ensures the JSON file is converted correctly- both dathbases are the same shape.
json_df = pd.read_json('/content/drive/MyDrive/Essentis/data/reviews.json')

print(json_df.shape)
print(df.shape)

(256, 10)
(256, 10)

In [ ]:
# saves the CSV back into the drive folder.
import pandas as pd

df = pd.read_json('/content/drive/MyDrive/Essentis/data/reviews.json')
df.to_csv('/content/drive/MyDrive/Essentis/data/google_reviews.csv', index=False)

In [ ]:
# checks the folder contents- CSV is loaded.
import os

os.listdir('/content/drive/MyDrive/Essentis/data')

['reviews.json',
 'reviews_new.csv',
 'reviews_clean.csv',
 'master_reviews.csv',
 'google_reviews.csv']

## Create Google Reviews Dataframe

In [ ]:
# creates the database for google reviews
google_reviews_df = pd.read_csv('/content/drive/MyDrive/Essentis/data/google_reviews.csv')

In [ ]:
# check the df
google_reviews_df.head()

,reviewer_name,reviewer_profile_image,is_local_guide,review_count,rating,review_date,review_text,link,photo_count,review_images
0,irine divya,https://lh3.googleusercontent.com/a/ACg8ocK827...,False,5 reviews,5,a month ago,"I am a Data Analyst Bootcamp student, and my e...",https://www.google.com/maps/contrib/1028908243...,NaN,NaN
1,Asieh Sharifi,https://lh3.googleusercontent.com/a-/ALV-UjXnN...,True,44 reviews,5,a month ago,Great UX/UI Bootcamp ExperienceI attended the ...,https://www.google.com/maps/contrib/1134308022...,33 photos,NaN
2,Margarita M,https://lh3.googleusercontent.com/a-/ALV-UjUnh...,False,13 reviews,5,a month ago,I recently completed a UX/UI Product Design pr...,https://www.google.com/maps/contrib/1115744527...,104 photos,NaN
3,Marvin,https://lh3.googleusercontent.com/a-/ALV-UjWpD...,False,10 reviews,5,3 months ago,I completed the Full-Stack Web & App Developme...,https://www.google.com/maps/contrib/1168523753...,3 photos,NaN
4,Majdi Alachkar,https://lh3.googleusercontent.com/a-/ALV-UjX6p...,False,3 reviews,5,2 months ago,I completed the Data Science Bootcamp at WBS S...,https://www.google.com/maps/contrib/1021783225...,3 photos,NaN

This has successfully converted the reviews.json file to google_df

# Clean Reviews DF

## Import Clean Reviews CSV

In [ ]:
with open('/content/drive/MyDrive/Essentis/data/reviews_clean.csv', 'r') as f:
    for i in range(10):
        print(f"{i+1}: {f.readline()}")

1: Table 1

2: author;date;overall_experience;instructors;curriculum;job_assistance;title;review;verified;verification_source;role;course;format;source;Batch ID;

3: Giorgi Shakiashvili ;2020-06-16;5;5;5;5;The best bootcamp;I have taken the 15-week long course with WBS Coding School and I'm super excited to be one of the early graduates from that school. I have learned a lot of new things for my whole life and obtained essential tech knowledge and skills as a full-stack developer thanks to the well-designed curriculum and highly professional staff at the school. You are highly encouraged to go through this perfect experience!;FALSE;NaN;Graduate;Full-Stack Web & App;full-time;course_report;6137845007;

4: Anonymous;2020-06-16;5;NaN;5;5;"""The best bootcamp""";I have taken the 15-week long course at WBS Coding School and I should say I'm super excited to be one of the early graduates of that school. I have got acquainted with a lot of things and obtained some invaluable tech knowledge and skills as a full-stack developer thanks to the well-designed and adjusted learning programme and the professional instructors at the school. Highly recommended to go through it!;TRUE;NaN;NaN;Full-Stack Web & App;Unknown;switchup;;

5: Anonymous;2020-06-25;5;NaN;5;5;"""Awesome Experience""";I am a graduate of WBS coding school and highly recommend to start your career as a Web Developer from studying in WBS. I had an amazing opportunity to study there. I learned much more, than coding during 15 weeks.The teaching staff, structure of the lessons, career services and also the atmosphere ! Everything was perfect for studying.At the end of course, I would say that it totally worthed it. In this short amount of time, starting from scratch we learned everything, that are in demand in IT market. The technological stacks, we learned, are more than enough to start a new role as a Full Stack developer.My recommendation is 10/10.;TRUE;NaN;NaN;Full-Stack Web & App;Unknown;switchup;;

6: Greg ;2020-06-25;5;5;5;5;Great Experience ;"First thing you must learn reading this review, is that after studying in  WBS coding school  your life will change and you can’t live without coding afterwards. I had an amazing opportunity to study there. I learned much more, than coding during 15 weeks.The teaching staff, structure of the lessons, career services and also the atmosphere ! Everything was perfect for studying. And now I am a Full Stack developer starting a new career in IT world. My recommendation is...First thing you must learn reading this review, is that after studying in  WBS coding school  your life will change and you can’t live without coding afterwards. I had an amazing opportunity to study there. I learned much more, than coding during 15 weeks.The teaching staff, structure of the lessons, career services and also the atmosphere ! Everything was perfect for studying. And now I am a Full Stack developer starting a new career in IT world. My recommendation is 10/10.

7: Read MoreRead Less";FALSE;NaN;Full stack Developer;Full-Stack Web & App;full-time;course_report;;

8: Btissam Asbai ;2020-07-16;5;5;5;5;From zero to hero!;"I started this bootcamp with especially a lot of confusion about coding. All these youtube videos, mini bootcamps etc really made me feel like the dumbest person ever. While I was looking for a serious platform, I found out that at WBS school they were about to start with a Full Stack Web and App development boot camp. I previously did some other courses at WBS and they are really really good. So I went for the Coding Bootcamp with almost zero knowledge. The course is fas...I started this bootcamp with especially a lot of confusion about coding. All these youtube videos, mini bootcamps etc really made me feel like the dumbest person ever. While I was looking for a serious platform, I found out that at WBS school they were about to start with a Full Stack Web and App development boot camp. I previously did some other courses at WBS and they are really really good. So I went for the Coding Bootcamp with almost zero knowledge. The course is fast paced but the teachers are incredibly patient! They make sure you keep up and they have for every student an approach that suits them best. I never knew that I would be capable of learning and creating so much awesome stuff, just in 12 weeks!!The highlight and the biggest advantage that WBS Codingschool offers is definitely the last 3 weeks on Campus!! No other school offers a real life experience like this!! Being in a fancy „Vegetarian-hotel„ for 3 weeks, with your classmates, teacher and coaches for 3 weeks working on your final project, that is just awesome!! The team spirit, the live-coaching, your teacher and other teachers available on site to help you in every step of the way; that is priceless!!!I made friends for life, created awesome apps and am much more confident about my capabilities.And as cherry on the cake, I landed a job one week before end of the course.I can only recommend!Read MoreRead Less";FALSE;NaN;Applicant;Full-Stack Web & App;full-time;course_report;6137845014;

9: Anonymous;2020-08-07;4,7;NaN;5;5;"""I am so happy that WBS Coding school took me on the journey""";All Staff member are very helpful. They work on equiping you with the starter-set of skills to become a Full-Stack developer. Also the mobile working style in team will make you familiar with future commercial projects. This is only the start of the journey and I am happy that WBS Coding school was on board with me. Kim;TRUE;NaN;NaN;Full-Stack Web & App;Unknown;switchup;;

10: Chris Steiner ;2020-09-21;5;5;5;5;Intense, challenging and totally worth it!;"I took the class after leaving my job as a product owner, so i had already some technical understanding. Our class overall had a very strong understanding, so we could keep the pace up. I learned so much in these weeks, more then i thought it is possible. It was very challenging, but worth every minute. Our teacher was amazing, the campus time in Berlin was great and the staff is very supportive. The downside is what i wrote earlier, it is very challenging, so be prepared to get stressed...I took the class after leaving my job as a product owner, so i had already some technical understanding. Our class overall had a very strong understanding, so we could keep the pace up. I learned so much in these weeks, more then i thought it is possible. It was very challenging, but worth every minute. Our teacher was amazing, the campus time in Berlin was great and the staff is very supportive. The downside is what i wrote earlier, it is very challenging, so be prepared to get stressed.I was able to get a full stack developer job within 2 months after the class and i feel well prepared for that.

## Create Clean Reviews Dataframe

In [ ]:
# specify delimeriters, since our source data is formatted inconsistently
import pandas as pd

clean_reviews_df = pd.read_csv(
    '/content/drive/MyDrive/Essentis/data/reviews_clean.csv',
    sep=';',                # semicolon delimiter
    engine='python',        # better handling of multi-line text
    quotechar='"',          # handle quotes properly
    skiprows=1,             # skip first row ("Table 1")
    on_bad_lines='warn'     # warns about bad lines but continues
)

sep=';' → semicolon-delimited

engine='python' → more forgiving parser

quotechar='"' → handle quotes properly

on_bad_lines='skip' → optional, skips truly broken rows

skiprows=1 → if you want to ignore that first line "Table 1"

In [ ]:
print(clean_reviews_df.shape)
clean_reviews_df.head()

(541, 16)

,author,date,overall_experience,instructors,curriculum,job_assistance,title,review,verified,verification_source,role,course,format,source,Batch ID,Unnamed: 15
0,Giorgi Shakiashvili,2020-06-16,5,5.0,5,5,The best bootcamp,I have taken the 15-week long course with WBS ...,False,NaN,Graduate,Full-Stack Web & App,full-time,course_report,6.137845e+09,NaN
1,Anonymous,2020-06-16,5,NaN,5,5,"""The best bootcamp""",I have taken the 15-week long course at WBS Co...,True,NaN,NaN,Full-Stack Web & App,Unknown,switchup,NaN,NaN
2,Anonymous,2020-06-25,5,NaN,5,5,"""Awesome Experience""",I am a graduate of WBS coding school and highl...,True,NaN,NaN,Full-Stack Web & App,Unknown,switchup,NaN,NaN
3,Greg,2020-06-25,5,5.0,5,5,Great Experience,First thing you must learn reading this review...,False,NaN,Full stack Developer,Full-Stack Web & App,full-time,course_report,NaN,NaN
4,Btissam Asbai,2020-07-16,5,5.0,5,5,From zero to hero!,I started this bootcamp with especially a lot ...,False,NaN,Applicant,Full-Stack Web & App,full-time,course_report,6.137845e+09,NaN

# New Reviews DF

## Import New Reviews CSV

In [ ]:
with open('/content/drive/MyDrive/Essentis/data/reviews_new.csv', 'r') as f:
    for i in range(10):
        print(f"{i+1}: {f.readline()}")

1: Table 1

2: source;author;date;course;format;title;review;overall_experience;curriculum;job_assistance;Review Author;Closest Match;Similarity Score;Batch ID;Review Author;Closest Match;Similarity Score

3: switchup;Irine Divya Peter;2025-12-17;Unknown;Unknown;"""Data Analyst Bootcamp""";I am a Data Analyst student, and my experience with WBS Coding School has been excellent. The instructors are very helpful, polite, and friendly. A special thanks to Instructor Christopher for his outstanding support.After a long gap, this course served as a great recap for me, and I learned a lot. The program was well structured and supported by high-quality learning materials. I would strongly recommend WBS Coding School to anyone who is willing to learn—it is a great place to start.;4,7;5;4;Irine Divya Peter;NaN;NaN;;;;

4: switchup;Anila Saifan;2025-12-15;Unknown;Unknown;"""A Challenging, Inspiring and Career-Focused Bootcamp Experience""";I recently finished the Full Stack Web Development Bootcamp at WBS Coding School, and it exceeded my expectations. I started the program with little to no coding experience, yet by the end I had built a strong foundation in web development.The pace was fast and demanding, but also incredibly engaging and motivating. In a short amount of time, I learned far more than I thought possible. The instructors were highly skilled and genuinely invested in helping students grow and succeed.What stood out most was the use of modern technologies and real-world coding practices, along with the strong focus on collaboration and hands-on projects. The career coaching support was especially valuable. The career coaches provided clear guidance on CV and LinkedIn optimization, interview preparation, and job search strategies. Their personalized feedback and ongoing support helped me better understand the job market and feel confident and prepared to take the next step in my tech career.;4,7;4;5;Anila Saifan;NaN;NaN;;;;

5: switchup;Margarita Miloserdova;2025-12-12;Product Design;full-time;"""UX/ UI Product Design Course""";I had the privilege of completing a UX/UI Product Design program at this outstanding school. From the very beginning, I felt confident in my choice, and the experience consistently exceeded my expectations. Despite starting without prior background in the field, the program enabled me to develop strong competencies within a relatively short period of 15 weeks.What I valued most was the thoughtful design of the curriculum. The combination of well-structured theoretical content, practical assignments rooted in real design challenges, and continuous collaboration with peers created an environment that encouraged both professional and personal growth. These elements allowed me to build technical skills while also strengthening my communication, teamwork, and problem-solving abilities.I am especially appreciative of my instructor, Ana, whose guidance played a significant role throughout the course. Her constructive feedback, accessibility, and commitment to our progress made a substantial difference. The Career Days were another valuable component, providing insights and resources that were directly applicable to future professional development.Overall, this program became an important step in my transition into the design field, and I am sincerely grateful for the knowledge, support, and opportunities I received.;5;5;5;Margarita Miloserdova;Magdeburg;40;481647845105;;;

6: switchup;Asieh Sharifi darani;2025-12-12;Product Design;full-time;"""Professional, Well-Organized, and Supportive""";I enrolled in the 15-week UX/UI Product Design bootcamp at WBS Coding School in August 2025, and my overall experience has been very positive.The program was clearly structured and well organized, which made the intensive format manageable. Everything ran smoothly, and the team was consistently responsive, professional, and approachable whenever support or clarification was needed.The projects were engaging, varied, and practical, covering different areas of UX/UI design and encouraging hands-on learning rather than just theory. The exercises and regular practice helped reinforce concepts effectively.The instructors were friendly, experienced, and professional, with a modern teaching approach aligned with current industry standards. Feedback was timely and constructive, which helped me improve throughout the course.The learning environment was collaborative and friendly, creating a motivating atmosphere despite the intensity of the bootcamp. Overall, I’m satisfied with my experience and would recommend WBS Coding School to anyone looking for a structured and supportive UX/UI program.;5;5;5;Asieh Sharifi darani;Braunschweig;43;481647845112;;;

7: switchup;Daria S;2025-12-10;Unknown;Unknown;"""Attended AI for Business course: Very satisfied, would recommend""";I Attended AI for Business course but it‘s not in the options in the dropdown for the courses. Structure of the course was very well made, starting with theory and small bits of information and small implementation task every day, and building up to bigger projects which include different skills and methods learned, The projects are very relevant and valuable for life outside the classroom, skills learned are very practical. The instructor was very helpful every step of the way.;4,3;5;3;Daria S;NaN;NaN;;;;

8: switchup;Hema Gunasekaran;2025-11-27;Unknown;Unknown;"""Completed course at WBS Coding School""";I recently completed the Data Science & Artificial Intelligence bootcamp at WBS Coding School, and it has been one of the best learning decisions I’ve made.The program combines strong theoretical foundations with a lot of practical, real-world projects in Python, SQL, Machine Learning and Data Engineering. The instructors were always patient and supportive, and the learning environment was friendly and motivating.What I appreciated the most was the structure of the program — especially the final project phase and the guidance from the career services team. They supported me with my CV, LinkedIn profile, job search strategy, and finding an internship.Overall, I highly recommend WBS Coding School to anyone who wants to break into Data Science or AI. It’s intense, but absolutely worth it!;5;5;0;Hema Gunasekaran;NaN;NaN;;;;

9: switchup;Lana;2025-11-17;Unknown;Unknown;"""Data Analytics Bootcamp""";Just wrapped up the WBS Coding School Data Analytics Bootcamp — and I can genuinely recommend it to anyone thinking of switching into data.The program is well-structured, fast-paced, and full of practical, real-world tasks that helped me build confidence working with tools like SQL, Python, Tableau, and Looker Studio.The career support was another big plus: great guidance on CVs, LinkedIn, mock interviews, and how to present your portfolio to future employers.Special thanks to our wonderful instructors — Mersiha, Sama, and Guy — for making complex topics feel approachable and for creating such a supportive learning environment.;5;5;5;Lana;NaN;NaN;;;;

10: switchup;Alaa Shaikhqasem;2025-11-17;Unknown;Unknown;"""Practical, Well-Planned, and Rewarding Course""";I completed WBS School’s Data Analytics Bootcamp and had a fantastic experience. The course is very well structured, with a thoughtful balance between workload and learning curve. The instructors are extremely dedicated and approachable, providing guidance every step of the way.The learning materials are modern, continuously updated, and perfectly suited to the pace of the course. Overall, it was an engaging and highly rewarding journey. I would definitely recommend this course to anyone looking to develop practical data analytics skills.;4,7;4;5;Alaa Shaikhqasem;NaN;NaN;;;;

## Create New Reviews Dataframe

In [ ]:
import pandas as pd

new_reviews_df = pd.read_csv(
    '/content/drive/MyDrive/Essentis/data/reviews_new.csv',
    sep=';',                     # semicolon delimiter
    engine='python',             # handle multi-line text safely
    quotechar='"',               # handle quotes properly
    skiprows=1,                  # skip first row ("Table 1")
    on_bad_lines='warn'          # warn about broken lines but continue
)

# Optional: drop empty trailing columns
new_reviews_df = new_reviews_df.loc[:, new_reviews_df.columns.str.strip() != '']

# Quick check
print(new_reviews_df.shape)
print(new_reviews_df.columns)
new_reviews_df.head()

(49, 17)
Index(['source', 'author', 'date', 'course', 'format', 'title', 'review',
       'overall_experience', 'curriculum', 'job_assistance', 'Review Author',
       'Closest Match', 'Similarity Score', 'Batch ID', 'Review Author.1',
       'Closest Match.1', 'Similarity Score.1'],
      dtype='object')

,source,author,date,course,format,title,review,overall_experience,curriculum,job_assistance,Review Author,Closest Match,Similarity Score,Batch ID,Review Author.1,Closest Match.1,Similarity Score.1
0,switchup,Irine Divya Peter,2025-12-17,Unknown,Unknown,"""Data Analyst Bootcamp""","I am a Data Analyst student, and my experience...","4,7",5,4,Irine Divya Peter,NaN,NaN,NaN,NaN,NaN,NaN
1,switchup,Anila Saifan,2025-12-15,Unknown,Unknown,"""A Challenging, Inspiring and Career-Focused B...",I recently finished the Full Stack Web Develop...,"4,7",4,5,Anila Saifan,NaN,NaN,NaN,NaN,NaN,NaN
2,switchup,Margarita Miloserdova,2025-12-12,Product Design,full-time,"""UX/ UI Product Design Course""",I had the privilege of completing a UX/UI Prod...,5,5,5,Margarita Miloserdova,Magdeburg,40.0,4.816478e+11,NaN,NaN,NaN
3,switchup,Asieh Sharifi darani,2025-12-12,Product Design,full-time,"""Professional, Well-Organized, and Supportive""",I enrolled in the 15-week UX/UI Product Design...,5,5,5,Asieh Sharifi darani,Braunschweig,43.0,4.816478e+11,NaN,NaN,NaN
4,switchup,Daria S,2025-12-10,Unknown,Unknown,"""Attended AI for Business course: Very satisfi...",I Attended AI for Business course but it‘s not...,"4,3",5,3,Daria S,NaN,NaN,NaN,NaN,NaN,NaN

engine='python' allows pandas to handle line breaks inside quotes, which the default C engine chokes on.

sep=';' fixes the field parsing.

skiprows=1 ignores the "Table 1" line.

on_bad_lines='warn' ensures it won’t crash if a tiny row is malformed.

Dropping empty columns fixes trailing semicolons in the header.

the reviews_new.csv is now new_reviews_df

# Combined DF

In [ ]:
# adds a source column to the master dataframe
google_reviews_df['data_source'] = 'google'
clean_reviews_df['data_source'] = 'clean'
new_reviews_df['data_source'] = 'new'

In [ ]:
import pandas as pd

master_reviews_df = pd.concat(
    [google_reviews_df, clean_reviews_df, new_reviews_df],
    ignore_index=True,   # resets the row index
    sort=False           # keeps columns as-is if some columns differ
)

In [ ]:
print(master_reviews_df.shape)       # total rows and columns
print(master_reviews_df.columns)     # check all column names
master_reviews_df['source'].value_counts()  # see how many rows came from each CSV

(846, 32)
Index(['reviewer_name', 'reviewer_profile_image', 'is_local_guide',
       'review_count', 'rating', 'review_date', 'review_text', 'link',
       'photo_count', 'review_images', 'source', 'author', 'date',
       'overall_experience', 'instructors', 'curriculum', 'job_assistance',
       'title', 'review', 'verified', 'verification_source', 'role', 'course',
       'format', 'Batch ID', 'Unnamed: 15', 'Review Author', 'Closest Match',
       'Similarity Score', 'Review Author.1', 'Closest Match.1',
       'Similarity Score.1'],
      dtype='object')

source
clean     541
google    256
new        49
Name: count, dtype: int64

This shows all the columns in all of our datasets- giving an overview of inconsistencies which need cleaning.

## Create Master Dataframe CSV

In [ ]:
master_reviews_df.to_csv(
    '/content/drive/MyDrive/Essentis/data/master_reviews.csv',
    index=False,
    sep=';',  # keep semicolon consistent if needed
    quoting=1  # quote all fields to be safe
)

This master dataframe can now be read as a csv and used for cleaning the data.